#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 3

#define MASTER_LEFT

#undef ENCODERS_PAD_A
#undef ENCODERS_PAD_B

#define ENCODERS_PAD_A { NO_PIN }
#define ENCODERS_PAD_B { NO_PIN }
#define ENCODERS_PAD_A_RIGHT { F4 }
#define ENCODERS_PAD_B_RIGHT { F5 }
#define ENCODER_RESOLUTION 4